window.ChemicalsDB = {
  // ============================================================
  // CATEGORY 1: ALKALI & ALKALINE EARTH METALS
  // ============================================================
  lithium: {
    id: "lithium",
    name: "Lithium Metal",
    formula: "Li",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 6.94,
    density: 0.534,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 3.58,
    solubility: 0.0001,
    flameColor: "crimson",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  sodium: {
    id: "sodium",
    name: "Sodium Metal",
    formula: "Na",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 22.99,
    density: 0.968,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 1.23,
    solubility: 0.0001,
    flameColor: "yellow",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  potassium: {
    id: "potassium",
    name: "Potassium Metal",
    formula: "K",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 39.10,
    density: 0.862,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.75,
    solubility: 0.0001,
    flameColor: "lilac",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  rubidium: {
    id: "rubidium",
    name: "Rubidium Metal",
    formula: "Rb",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 85.47,
    density: 1.532,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.36,
    solubility: 0.0001,
    flameColor: "red-violet",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  cesium: {
    id: "cesium",
    name: "Cesium Metal",
    formula: "Cs",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 132.91,
    density: 1.93,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.24,
    solubility: 0.0001,
    flameColor: "blue",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  beryllium: {
    id: "beryllium",
    name: "Beryllium Metal",
    formula: "Be",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 9.01,
    density: 1.85,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 1.82,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },
  magnesium: {
    id: "magnesium",
    name: "Magnesium Metal",
    formula: "Mg",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 24.31,
    density: 1.74,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 1.02,
    solubility: 0.0001,
    flameColor: "brilliant white",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  calcium: {
    id: "calcium",
    name: "Calcium Metal",
    formula: "Ca",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 40.08,
    density: 1.55,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.63,
    solubility: 0.0001,
    flameColor: "orange-red",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  strontium: {
    id: "strontium",
    name: "Strontium Metal",
    formula: "Sr",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 87.62,
    density: 2.64,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.30,
    solubility: 0.0001,
    flameColor: "crimson",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  barium: {
    id: "barium",
    name: "Barium Metal",
    formula: "Ba",
    category: "Alkali & Alkaline Earth Metals",
    state: "solid",
    molarMass: 137.33,
    density: 3.62,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.20,
    solubility: 0.0001,
    flameColor: "apple green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },

  // ============================================================
  // CATEGORY 2: TRANSITION & POST-TRANSITION METALS
  // ============================================================
  iron: {
    id: "iron",
    name: "Iron Metal",
    formula: "Fe",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 55.85,
    density: 7.87,
    color: "#8B8B8B",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.45,
    solubility: 0.0001,
    flameColor: "golden",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  copper: {
    id: "copper",
    name: "Copper Metal",
    formula: "Cu",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 63.55,
    density: 8.96,
    color: "#B87333",
    solutionColor: "blue",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.385,
    solubility: 0.0001,
    flameColor: "blue-green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  zinc: {
    id: "zinc",
    name: "Zinc Metal",
    formula: "Zn",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 65.38,
    density: 7.14,
    color: "#A0A0A0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.388,
    solubility: 0.0001,
    flameColor: "blue-green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  silver: {
    id: "silver",
    name: "Silver Metal",
    formula: "Ag",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 107.87,
    density: 10.50,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.235,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  gold: {
    id: "gold",
    name: "Gold Metal",
    formula: "Au",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 196.97,
    density: 19.30,
    color: "#FFD700",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.129,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  aluminum: {
    id: "aluminum",
    name: "Aluminum Metal",
    formula: "Al",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 26.98,
    density: 2.70,
    color: "#D3D3D3",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.897,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  lead: {
    id: "lead",
    name: "Lead Metal",
    formula: "Pb",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 207.2,
    density: 11.34,
    color: "#5A5A5A",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.128,
    solubility: 0.0001,
    flameColor: "gray-white",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },
  tin: {
    id: "tin",
    name: "Tin Metal",
    formula: "Sn",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 118.71,
    density: 7.31,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.228,
    solubility: 0.0001,
    flameColor: "blue-green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  manganese: {
    id: "manganese",
    name: "Manganese Metal",
    formula: "Mn",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 54.94,
    density: 7.21,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.479,
    solubility: 0.0001,
    flameColor: "yellow-green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  chromium: {
    id: "chromium",
    name: "Chromium Metal",
    formula: "Cr",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 52.00,
    density: 7.19,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.449,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  platinum: {
    id: "platinum",
    name: "Platinum Metal",
    formula: "Pt",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 195.08,
    density: 21.45,
    color: "#E5E4E2",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.133,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  nickel: {
    id: "nickel",
    name: "Nickel Metal",
    formula: "Ni",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 58.69,
    density: 8.90,
    color: "#C0C0C0",
    solutionColor: "green",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.444,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  cobalt: {
    id: "cobalt",
    name: "Cobalt Metal",
    formula: "Co",
    category: "Transition & Post-Transition Metals",
    state: "solid",
    molarMass: 58.93,
    density: 8.90,
    color: "#C0C0C0",
    solutionColor: "pink",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.421,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  mercury: {
    id: "mercury",
    name: "Mercury Metal",
    formula: "Hg",
    category: "Transition & Post-Transition Metals",
    state: "liquid",
    molarMass: 200.59,
    density: 13.59,
    color: "#C0C0C0",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.140,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },

  // ============================================================
  // CATEGORY 3: NON-METALS & HALOGENS
  // ============================================================
  carbon: {
    id: "carbon",
    name: "Carbon",
    formula: "C",
    category: "Non-Metals & Halogens",
    state: "solid",
    molarMass: 12.01,
    density: 2.26,
    color: "#000000",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.709,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  hydrogen: {
    id: "hydrogen",
    name: "Hydrogen Gas",
    formula: "H₂",
    category: "Non-Metals & Halogens",
    state: "gas",
    molarMass: 2.02,
    density: 0.00008988,
    color: "colorless",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 14.30,
    solubility: 0.0002,
    flameColor: "pale blue",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  nitrogen: {
    id: "nitrogen",
    name: "Nitrogen Gas",
    formula: "N₂",
    category: "Non-Metals & Halogens",
    state: "gas",
    molarMass: 28.01,
    density: 0.0012506,
    color: "colorless",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 1.042,
    solubility: 0.0002,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  oxygen: {
    id: "oxygen",
    name: "Oxygen Gas",
    formula: "O₂",
    category: "Non-Metals & Halogens",
    state: "gas",
    molarMass: 32.00,
    density: 0.001429,
    color: "colorless",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.918,
    solubility: 0.0043,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  fluorine: {
    id: "fluorine",
    name: "Fluorine Gas",
    formula: "F₂",
    category: "Non-Metals & Halogens",
    state: "gas",
    molarMass: 38.00,
    density: 0.001696,
    color: "pale yellow-green",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.824,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },
  chlorine: {
    id: "chlorine",
    name: "Chlorine Gas",
    formula: "Cl₂",
    category: "Non-Metals & Halogens",
    state: "gas",
    molarMass: 70.90,
    density: 0.003214,
    color: "pale yellow-green",
    solutionColor: "pale yellow",
    ph: 2.0,
    enthalpyFormation: 0,
    specificHeat: 0.479,
    solubility: 0.73,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },
  bromine: {
    id: "bromine",
    name: "Bromine Liquid",
    formula: "Br₂",
    category: "Non-Metals & Halogens",
    state: "liquid",
    molarMass: 159.80,
    density: 3.12,
    color: "#8B0000",
    solutionColor: "orange-brown",
    ph: 1.5,
    enthalpyFormation: 0,
    specificHeat: 0.226,
    solubility: 3.41,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },
  iodine: {
    id: "iodine",
    name: "Iodine Solid",
    formula: "I₂",
    category: "Non-Metals & Halogens",
    state: "solid",
    molarMass: 253.81,
    density: 4.93,
    color: "#4B0082",
    solutionColor: "brown",
    ph: 5.0,
    enthalpyFormation: 0,
    specificHeat: 0.214,
    solubility: 0.03,
    flameColor: "violet",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },
  phosphorus: {
    id: "phosphorus",
    name: "Phosphorus (White)",
    formula: "P₄",
    category: "Non-Metals & Halogens",
    state: "solid",
    molarMass: 123.90,
    density: 1.82,
    color: "#FFE4B5",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.769,
    solubility: 0.0001,
    flameColor: "green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: true,
      acidBaseType: null
    }
  },
  sulfur: {
    id: "sulfur",
    name: "Sulfur",
    formula: "S₈",
    category: "Non-Metals & Halogens",
    state: "solid",
    molarMass: 256.52,
    density: 2.07,
    color: "#FFD700",
    solutionColor: "colorless",
    ph: null,
    enthalpyFormation: 0,
    specificHeat: 0.705,
    solubility: 0.0001,
    flameColor: "blue",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: true,
      acidBaseType: null
    }
  },

  // ============================================================
  // CATEGORY 4: BASIC OXIDES
  // ============================================================
  sodium_oxide: {
    id: "sodium_oxide",
    name: "Sodium Oxide",
    formula: "Na₂O",
    category: "Basic Oxides",
    state: "solid",
    molarMass: 61.98,
    density: 2.27,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 14.0,
    enthalpyFormation: -414.2,
    specificHeat: 0.70,
    solubility: 9999,
    flameColor: "yellow",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "basic_oxide"
    }
  },
  potassium_oxide: {
    id: "potassium_oxide",
    name: "Potassium Oxide",
    formula: "K₂O",
    category: "Basic Oxides",
    state: "solid",
    molarMass: 94.20,
    density: 2.35,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 14.0,
    enthalpyFormation: -361.5,
    specificHeat: 0.65,
    solubility: 9999,
    flameColor: "lilac",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "basic_oxide"
    }
  },
  calcium_oxide: {
    id: "calcium_oxide",
    name: "Calcium Oxide (Quicklime)",
    formula: "CaO",
    category: "Basic Oxides",
    state: "solid",
    molarMass: 56.08,
    density: 3.34,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 12.5,
    enthalpyFormation: -635.1,
    specificHeat: 0.75,
    solubility: 0.13,
    flameColor: "orange-red",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "basic_oxide"
    }
  },
  magnesium_oxide: {
    id: "magnesium_oxide",
    name: "Magnesium Oxide",
    formula: "MgO",
    category: "Basic Oxides",
    state: "solid",
    molarMass: 40.30,
    density: 3.58,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 10.0,
    enthalpyFormation: -601.6,
    specificHeat: 0.92,
    solubility: 0.0006,
    flameColor: "brilliant white",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "basic_oxide"
    }
  },
  barium_oxide: {
    id: "barium_oxide",
    name: "Barium Oxide",
    formula: "BaO",
    category: "Basic Oxides",
    state: "solid",
    molarMass: 153.33,
    density: 5.72,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 13.5,
    enthalpyFormation: -548.1,
    specificHeat: 0.48,
    solubility: 3.48,
    flameColor: "apple green",
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "basic_oxide"
    }
  },

  // ============================================================
  // CATEGORY 5: ACIDIC OXIDES
  // ============================================================
  sulfur_dioxide: {
    id: "sulfur_dioxide",
    name: "Sulfur Dioxide",
    formula: "SO₂",
    category: "Acidic Oxides",
    state: "gas",
    molarMass: 64.07,
    density: 0.00263,
    color: "colorless",
    solutionColor: "colorless",
    ph: 2.5,
    enthalpyFormation: -296.8,
    specificHeat: 0.64,
    solubility: 11.3,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "acidic_oxide"
    }
  },
  sulfur_trioxide: {
    id: "sulfur_trioxide",
    name: "Sulfur Trioxide",
    formula: "SO₃",
    category: "Acidic Oxides",
    state: "liquid",
    molarMass: 80.06,
    density: 1.92,
    color: "colorless",
    solutionColor: "colorless",
    ph: 1.0,
    enthalpyFormation: -396.0,
    specificHeat: 0.71,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "acidic_oxide"
    }
  },
  carbon_dioxide: {
    id: "carbon_dioxide",
    name: "Carbon Dioxide",
    formula: "CO₂",
    category: "Acidic Oxides",
    state: "gas",
    molarMass: 44.01,
    density: 0.001977,
    color: "colorless",
    solutionColor: "colorless",
    ph: 5.6,
    enthalpyFormation: -393.5,
    specificHeat: 0.84,
    solubility: 0.145,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "acidic_oxide"
    }
  },
  nitrogen_dioxide: {
    id: "nitrogen_dioxide",
    name: "Nitrogen Dioxide",
    formula: "NO₂",
    category: "Acidic Oxides",
    state: "gas",
    molarMass: 46.01,
    density: 0.00188,
    color: "#8B4513",
    solutionColor: "yellow-brown",
    ph: 2.0,
    enthalpyFormation: 33.2,
    specificHeat: 0.77,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "acidic_oxide"
    }
  },
  phosphorus_pentoxide: {
    id: "phosphorus_pentoxide",
    name: "Phosphorus Pentoxide",
    formula: "P₄O₁₀",
    category: "Acidic Oxides",
    state: "solid",
    molarMass: 283.89,
    density: 2.39,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 1.0,
    enthalpyFormation: -2984.0,
    specificHeat: 0.84,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "acidic_oxide"
    }
  },
  dinitrogen_pentoxide: {
    id: "dinitrogen_pentoxide",
    name: "Dinitrogen Pentoxide",
    formula: "N₂O₅",
    category: "Acidic Oxides",
    state: "solid",
    molarMass: 108.01,
    density: 1.64,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 1.0,
    enthalpyFormation: -43.1,
    specificHeat: 0.80,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "acidic_oxide"
    }
  },

  // ============================================================
  // CATEGORY 6: AMPHOTERIC & NEUTRAL OXIDES
  // ============================================================
  aluminum_oxide: {
    id: "aluminum_oxide",
    name: "Aluminum Oxide (Alumina)",
    formula: "Al₂O₃",
    category: "Amphoteric & Neutral Oxides",
    state: "solid",
    molarMass: 101.96,
    density: 3.95,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -1675.7,
    specificHeat: 0.88,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  zinc_oxide: {
    id: "zinc_oxide",
    name: "Zinc Oxide",
    formula: "ZnO",
    category: "Amphoteric & Neutral Oxides",
    state: "solid",
    molarMass: 81.38,
    density: 5.61,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -350.5,
    specificHeat: 0.49,
    solubility: 0.0004,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  lead_oxide: {
    id: "lead_oxide",
    name: "Lead(II) Oxide",
    formula: "PbO",
    category: "Amphoteric & Neutral Oxides",
    state: "solid",
    molarMass: 223.20,
    density: 9.53,
    color: "#FFFF00",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -217.3,
    specificHeat: 0.21,
    solubility: 0.0017,
    flameColor: "gray-white",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },
  carbon_monoxide: {
    id: "carbon_monoxide",
    name: "Carbon Monoxide",
    formula: "CO",
    category: "Amphoteric & Neutral Oxides",
    state: "gas",
    molarMass: 28.01,
    density: 0.00125,
    color: "colorless",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -110.5,
    specificHeat: 1.04,
    solubility: 0.0026,
    flameColor: "blue",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: true,
      acidBaseType: null
    }
  },
  nitric_oxide: {
    id: "nitric_oxide",
    name: "Nitric Oxide",
    formula: "NO",
    category: "Amphoteric & Neutral Oxides",
    state: "gas",
    molarMass: 30.01,
    density: 0.00134,
    color: "colorless",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: 90.2,
    specificHeat: 0.97,
    solubility: 0.0056,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: null
    }
  },
  nitrous_oxide: {
    id: "nitrous_oxide",
    name: "Nitrous Oxide (Laughing Gas)",
    formula: "N₂O",
    category: "Amphoteric & Neutral Oxides",
    state: "gas",
    molarMass: 44.01,
    density: 0.00198,
    color: "colorless",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: 82.1,
    specificHeat: 0.88,
    solubility: 0.12,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },

  // ============================================================
  // CATEGORY 7: STRONG & WEAK ACIDS
  // ============================================================
  hydrochloric_acid: {
    id: "hydrochloric_acid",
    name: "Hydrochloric Acid",
    formula: "HCl",
    category: "Strong & Weak Acids",
    state: "aqueous",
    molarMass: 36.46,
    density: 1.18,
    color: "colorless",
    solutionColor: "colorless",
    ph: 0.0,
    enthalpyFormation: -92.3,
    specificHeat: 0.80,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "strong_acid"
    }
  },
  sulfuric_acid: {
    id: "sulfuric_acid",
    name: "Sulfuric Acid",
    formula: "H₂SO₄",
    category: "Strong & Weak Acids",
    state: "liquid",
    molarMass: 98.08,
    density: 1.84,
    color: "colorless",
    solutionColor: "colorless",
    ph: 0.0,
    enthalpyFormation: -814.0,
    specificHeat: 1.38,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "strong_acid"
    }
  },
  nitric_acid: {
    id: "nitric_acid",
    name: "Nitric Acid",
    formula: "HNO₃",
    category: "Strong & Weak Acids",
    state: "liquid",
    molarMass: 63.01,
    density: 1.51,
    color: "colorless",
    solutionColor: "colorless",
    ph: 0.0,
    enthalpyFormation: -174.1,
    specificHeat: 1.72,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "strong_acid"
    }
  },
  hydrofluoric_acid: {
    id: "hydrofluoric_acid",
    name: "Hydrofluoric Acid",
    formula: "HF",
    category: "Strong & Weak Acids",
    state: "aqueous",
    molarMass: 20.01,
    density: 1.15,
    color: "colorless",
    solutionColor: "colorless",
    ph: 2.0,
    enthalpyFormation: -320.0,
    specificHeat: 2.50,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "weak_acid"
    }
  },
  acetic_acid: {
    id: "acetic_acid",
    name: "Acetic Acid",
    formula: "CH₃COOH",
    category: "Strong & Weak Acids",
    state: "liquid",
    molarMass: 60.05,
    density: 1.05,
    color: "colorless",
    solutionColor: "colorless",
    ph: 2.4,
    enthalpyFormation: -487.0,
    specificHeat: 2.18,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: true,
      toxicGas: false,
      combustible: true,
      acidBaseType: "weak_acid"
    }
  },
  phosphoric_acid: {
    id: "phosphoric_acid",
    name: "Phosphoric Acid",
    formula: "H₃PO₄",
    category: "Strong & Weak Acids",
    state: "liquid",
    molarMass: 98.00,
    density: 1.70,
    color: "colorless",
    solutionColor: "colorless",
    ph: 1.5,
    enthalpyFormation: -1288.0,
    specificHeat: 2.20,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "weak_acid"
    }
  },
  carbonic_acid: {
    id: "carbonic_acid",
    name: "Carbonic Acid",
    formula: "H₂CO₃",
    category: "Strong & Weak Acids",
    state: "aqueous",
    molarMass: 62.03,
    density: 1.00,
    color: "colorless",
    solutionColor: "colorless",
    ph: 3.6,
    enthalpyFormation: -699.7,
    specificHeat: 4.18,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "weak_acid"
    }
  },
  sulfurous_acid: {
    id: "sulfurous_acid",
    name: "Sulfurous Acid",
    formula: "H₂SO₃",
    category: "Strong & Weak Acids",
    state: "aqueous",
    molarMass: 82.08,
    density: 1.03,
    color: "colorless",
    solutionColor: "colorless",
    ph: 1.8,
    enthalpyFormation: -608.8,
    specificHeat: 3.50,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "weak_acid"
    }
  },

  // ============================================================
  // CATEGORY 8: STRONG & WEAK BASES
  // ============================================================
  sodium_hydroxide: {
    id: "sodium_hydroxide",
    name: "Sodium Hydroxide (Caustic Soda)",
    formula: "NaOH",
    category: "Strong & Weak Bases",
    state: "solid",
    molarMass: 40.00,
    density: 2.13,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 14.0,
    enthalpyFormation: -425.6,
    specificHeat: 1.50,
    solubility: 109.0,
    flameColor: "yellow",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "strong_base"
    }
  },
  potassium_hydroxide: {
    id: "potassium_hydroxide",
    name: "Potassium Hydroxide (Caustic Potash)",
    formula: "KOH",
    category: "Strong & Weak Bases",
    state: "solid",
    molarMass: 56.11,
    density: 2.04,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 14.0,
    enthalpyFormation: -425.8,
    specificHeat: 1.18,
    solubility: 112.0,
    flameColor: "lilac",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "strong_base"
    }
  },
  calcium_hydroxide: {
    id: "calcium_hydroxide",
    name: "Calcium Hydroxide (Slaked Lime)",
    formula: "Ca(OH)₂",
    category: "Strong & Weak Bases",
    state: "solid",
    molarMass: 74.09,
    density: 2.21,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 12.4,
    enthalpyFormation: -986.1,
    specificHeat: 1.20,
    solubility: 0.185,
    flameColor: "orange-red",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "strong_base"
    }
  },
  magnesium_hydroxide: {
    id: "magnesium_hydroxide",
    name: "Magnesium Hydroxide (Milk of Magnesia)",
    formula: "Mg(OH)₂",
    category: "Strong & Weak Bases",
    state: "solid",
    molarMass: 58.32,
    density: 2.34,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 10.5,
    enthalpyFormation: -924.5,
    specificHeat: 1.10,
    solubility: 0.0009,
    flameColor: "brilliant white",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "weak_base"
    }
  },
  ammonium_hydroxide: {
    id: "ammonium_hydroxide",
    name: "Ammonium Hydroxide",
    formula: "NH₄OH",
    category: "Strong & Weak Bases",
    state: "aqueous",
    molarMass: 35.05,
    density: 0.91,
    color: "colorless",
    solutionColor: "colorless",
    ph: 11.6,
    enthalpyFormation: -80.0,
    specificHeat: 4.18,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "weak_base"
    }
  },
  barium_hydroxide: {
    id: "barium_hydroxide",
    name: "Barium Hydroxide",
    formula: "Ba(OH)₂",
    category: "Strong & Weak Bases",
    state: "solid",
    molarMass: 171.34,
    density: 3.74,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 13.0,
    enthalpyFormation: -944.7,
    specificHeat: 0.90,
    solubility: 5.6,
    flameColor: "apple green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "strong_base"
    }
  },
  lithium_hydroxide: {
    id: "lithium_hydroxide",
    name: "Lithium Hydroxide",
    formula: "LiOH",
    category: "Strong & Weak Bases",
    state: "solid",
    molarMass: 23.95,
    density: 1.46,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 13.5,
    enthalpyFormation: -487.5,
    specificHeat: 1.90,
    solubility: 12.8,
    flameColor: "crimson",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "strong_base"
    }
  },

  // ============================================================
  // CATEGORY 9: SOLUBLE & INSOLUBLE SALTS
  // ============================================================
  sodium_chloride: {
    id: "sodium_chloride",
    name: "Sodium Chloride (Table Salt)",
    formula: "NaCl",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 58.44,
    density: 2.16,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -411.1,
    specificHeat: 0.86,
    solubility: 36.0,
    flameColor: "yellow",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  silver_nitrate: {
    id: "silver_nitrate",
    name: "Silver Nitrate",
    formula: "AgNO₃",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 169.87,
    density: 4.35,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 6.0,
    enthalpyFormation: -124.4,
    specificHeat: 0.70,
    solubility: 256.0,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  potassium_iodide: {
    id: "potassium_iodide",
    name: "Potassium Iodide",
    formula: "KI",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 166.00,
    density: 3.13,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -327.9,
    specificHeat: 0.53,
    solubility: 148.0,
    flameColor: "lilac",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  lead_nitrate: {
    id: "lead_nitrate",
    name: "Lead(II) Nitrate",
    formula: "Pb(NO₃)₂",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 331.20,
    density: 4.53,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 5.0,
    enthalpyFormation: -451.9,
    specificHeat: 0.40,
    solubility: 56.5,
    flameColor: "gray-white",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  copper_sulfate: {
    id: "copper_sulfate",
    name: "Copper(II) Sulfate Pentahydrate",
    formula: "CuSO₄·5H₂O",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 249.68,
    density: 2.29,
    color: "#00BFFF",
    solutionColor: "blue",
    ph: 4.0,
    enthalpyFormation: -2276.5,
    specificHeat: 0.63,
    solubility: 32.0,
    flameColor: "blue-green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  calcium_carbonate: {
    id: "calcium_carbonate",
    name: "Calcium Carbonate (Limestone)",
    formula: "CaCO₃",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 100.09,
    density: 2.71,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 9.0,
    enthalpyFormation: -1207.0,
    specificHeat: 0.84,
    solubility: 0.0013,
    flameColor: "orange-red",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  barium_sulfate: {
    id: "barium_sulfate",
    name: "Barium Sulfate (Barite)",
    formula: "BaSO₄",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 233.39,
    density: 4.49,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -1473.7,
    specificHeat: 0.47,
    solubility: 0.00024,
    flameColor: "apple green",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  iron_sulfate: {
    id: "iron_sulfate",
    name: "Iron(II) Sulfate Heptahydrate",
    formula: "FeSO₄·7H₂O",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 278.01,
    density: 1.90,
    color: "#7CFC00",
    solutionColor: "pale green",
    ph: 4.5,
    enthalpyFormation: -928.4,
    specificHeat: 0.60,
    solubility: 25.6,
    flameColor: "golden",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  potassium_permanganate: {
    id: "potassium_permanganate",
    name: "Potassium Permanganate",
    formula: "KMnO₄",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 158.03,
    density: 2.70,
    color: "#800080",
    solutionColor: "purple",
    ph: 6.0,
    enthalpyFormation: -813.4,
    specificHeat: 0.70,
    solubility: 6.4,
    flameColor: "lilac",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: "neutral_salt"
    }
  },
  iron_chloride: {
    id: "iron_chloride",
    name: "Iron(III) Chloride",
    formula: "FeCl₃",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 162.20,
    density: 2.90,
    color: "#8B4513",
    solutionColor: "yellow-brown",
    ph: 2.0,
    enthalpyFormation: -399.5,
    specificHeat: 0.65,
    solubility: 91.9,
    flameColor: "golden",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  sodium_carbonate: {
    id: "sodium_carbonate",
    name: "Sodium Carbonate (Washing Soda)",
    formula: "Na₂CO₃",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 105.99,
    density: 2.54,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 11.5,
    enthalpyFormation: -1130.8,
    specificHeat: 1.10,
    solubility: 21.5,
    flameColor: "yellow",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  sodium_bicarbonate: {
    id: "sodium_bicarbonate",
    name: "Sodium Bicarbonate (Baking Soda)",
    formula: "NaHCO₃",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 84.01,
    density: 2.20,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 8.5,
    enthalpyFormation: -950.8,
    specificHeat: 0.88,
    solubility: 9.6,
    flameColor: "yellow",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },
  ammonium_chloride: {
    id: "ammonium_chloride",
    name: "Ammonium Chloride (Sal Ammoniac)",
    formula: "NH₄Cl",
    category: "Soluble & Insoluble Salts",
    state: "solid",
    molarMass: 53.49,
    density: 1.53,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 5.0,
    enthalpyFormation: -314.4,
    specificHeat: 1.57,
    solubility: 29.7,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "neutral_salt"
    }
  },

  // ============================================================
  // CATEGORY 10: SOLVENTS & LIQUIDS
  // ============================================================
  water: {
    id: "water",
    name: "Water",
    formula: "H₂O",
    category: "Solvents & Liquids",
    state: "liquid",
    molarMass: 18.02,
    density: 1.00,
    color: "colorless",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -285.8,
    specificHeat: 4.18,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: true,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  },
  ethanol: {
    id: "ethanol",
    name: "Ethanol",
    formula: "C₂H₅OH",
    category: "Solvents & Liquids",
    state: "liquid",
    molarMass: 46.07,
    density: 0.789,
    color: "colorless",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -277.6,
    specificHeat: 2.44,
    solubility: 9999,
    flameColor: "blue",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: true,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  acetone: {
    id: "acetone",
    name: "Acetone",
    formula: "C₃H₆O",
    category: "Solvents & Liquids",
    state: "liquid",
    molarMass: 58.08,
    density: 0.785,
    color: "colorless",
    solutionColor: "colorless",
    ph: 7.0,
    enthalpyFormation: -248.1,
    specificHeat: 2.15,
    solubility: 9999,
    flameColor: "blue",
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: true,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  liquid_nitric_acid: {
    id: "liquid_nitric_acid",
    name: "Liquid Nitric Acid (Concentrated)",
    formula: "HNO₃ (l)",
    category: "Solvents & Liquids",
    state: "liquid",
    molarMass: 63.01,
    density: 1.51,
    color: "colorless",
    solutionColor: "colorless",
    ph: 0.0,
    enthalpyFormation: -174.1,
    specificHeat: 1.72,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "strong_acid"
    }
  },
  concentrated_sulfuric_acid: {
    id: "concentrated_sulfuric_acid",
    name: "Concentrated Sulfuric Acid",
    formula: "H₂SO₄ (conc.)",
    category: "Solvents & Liquids",
    state: "liquid",
    molarMass: 98.08,
    density: 1.84,
    color: "colorless",
    solutionColor: "colorless",
    ph: 0.0,
    enthalpyFormation: -814.0,
    specificHeat: 1.38,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: true,
      isSolvent: false,
      toxicGas: true,
      combustible: false,
      acidBaseType: "strong_acid"
    }
  },

  // ============================================================
  // CATEGORY 11: INDICATORS
  // ============================================================
  phenolphthalein: {
    id: "phenolphthalein",
    name: "Phenolphthalein",
    formula: "C₂₀H₁₄O₄",
    category: "Indicators",
    state: "solid",
    molarMass: 318.33,
    density: 1.30,
    color: "#FFFFFF",
    solutionColor: "colorless",
    ph: 9.3,
    enthalpyFormation: -800.0,
    specificHeat: 1.20,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  methyl_orange: {
    id: "methyl_orange",
    name: "Methyl Orange",
    formula: "C₁₄H₁₄N₃NaO₃S",
    category: "Indicators",
    state: "solid",
    molarMass: 327.33,
    density: 1.28,
    color: "#FFA500",
    solutionColor: "orange",
    ph: 3.7,
    enthalpyFormation: -900.0,
    specificHeat: 1.15,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  bromothymol_blue: {
    id: "bromothymol_blue",
    name: "Bromothymol Blue",
    formula: "C₂₇H₂₈Br₂O₅S",
    category: "Indicators",
    state: "solid",
    molarMass: 624.38,
    density: 1.25,
    color: "#0000FF",
    solutionColor: "blue",
    ph: 7.0,
    enthalpyFormation: -1500.0,
    specificHeat: 1.10,
    solubility: 0.0001,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: true,
      acidBaseType: null
    }
  },
  universal_indicator: {
    id: "universal_indicator",
    name: "Universal Indicator",
    formula: "Mixture",
    category: "Indicators",
    state: "liquid",
    molarMass: 300.0,
    density: 1.00,
    color: "#00FF00",
    solutionColor: "green",
    ph: 7.0,
    enthalpyFormation: -500.0,
    specificHeat: 4.00,
    solubility: 9999,
    flameColor: null,
    reactivity: {
      reactsViolentlyWithWater: false,
      isSolvent: false,
      toxicGas: false,
      combustible: false,
      acidBaseType: null
    }
  }
};
